### PR TITLE
Updating env and yml files according to latest system requirements of adobe commerce (magento open source) on-premises

### PR DESCRIPTION
**Pull request by lfluvisotto**
@navarr 

https://experienceleague.adobe.com/en/docs/commerce-operations/installation-guide/system-requirements

node lts

https://github.com/magento/magento-cloud-docker/blob/5177d6580c4d61cb6c7d5fab14d39748d68d1f65/images/php/8.3-cli/Dockerfile#L35

image

### CODE REVIEW

**Review by navarr — APPROVED** [review]
Looks great, thank you for the contribution!

Just needs a quick sanity test before merge

**Review by bap14 — APPROVED** [review]
Matches what is published by Adobe.

**Comment by bap14** [comment]
@navarr These versions match the latest 2.4.7 requirements.

**Comment by navarr** [comment]
Just want to verify that up runs without issues before merge.  I'll try to handle that next week.

**Review by navarr — APPROVED** [review]

**Pull request merged**
